build: Fix build when optimization is disabled
FORTIFY_SOURCE requires that optimization is enabled, and causes build
to fail when it isn't. For example, from config.log:

configure:12459: checking for signalfd
configure:12459: gcc -o conftest -Wall -O2 -D_FORTIFY_SOURCE=2 -Werror -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wdeclaration-after-statement -Wmissing-declarations -Wredundant-decls -Wcast-align -DG_DISABLE_DEPRECATED -O0 -g   conftest.c  >&5
In file included from /usr/include/limits.h:26:0,
                 from /usr/lib64/gcc/x86_64-pc-linux-gnu/4.7.2/include-fixed/limits.h:169,
                 from /usr/lib64/gcc/x86_64-pc-linux-gnu/4.7.2/include-fixed/syslimits.h:7,
                 from /usr/lib64/gcc/x86_64-pc-linux-gnu/4.7.2/include-fixed/limits.h:34,
                 from conftest.c:34:
/usr/include/features.h:330:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
cc1: all warnings being treated as errors